import type { NextPage } from 'next'
import Head from 'next/head'
import { Container }  from '../styles/app.style'
import Hero from '../Components/Hero/Hero'

const Home: NextPage = () => {
 


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Container>
        <Hero/>
      </Container>

    



   
   
   </>
       
  )
}

export default Home
